/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu May 07 09:17:29 GMT 2020
 */

package com.rakegroup;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class JoomlaOutput_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.rakegroup.JoomlaOutput"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/test-smell/generation-scripts/projects/16_templatedetails"); 
    java.lang.System.setProperty("sun.boot.class.path", "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/classes"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JoomlaOutput_ESTest_scaffolding.class.getClassLoader() ,
      "com.rakegroup.JoomlaOutput$Position",
      "org.jdom.output.XMLOutputter",
      "com.rakegroup.JoomlaOutput$Administration",
      "org.jdom.filter.ContentFilter",
      "org.jdom.ContentList$FilterListIterator",
      "org.jdom.Document",
      "org.jdom.JDOMException",
      "org.jdom.FilterIterator",
      "com.rakegroup.JoomlaOutput$Files",
      "org.jdom.Namespace",
      "org.jdom.Verifier",
      "org.jdom.IllegalNameException",
      "org.jdom.NamespaceKey",
      "org.jdom.ContentList$FilterList",
      "org.jdom.DescendantIterator",
      "com.rakegroup.JoomlaOutput$Version",
      "com.rakegroup.JoomlaOutput$Folder",
      "org.jdom.filter.ElementFilter",
      "org.jdom.IllegalDataException",
      "org.jdom.Text",
      "com.rakegroup.JoomlaOutput$Params",
      "org.jdom.Attribute",
      "com.rakegroup.JoomlaOutput$Name",
      "com.rakegroup.JoomlaOutput$SimpleElement",
      "org.jdom.Parent",
      "com.rakegroup.JoomlaOutput$Language",
      "com.rakegroup.JoomlaOutput$Author",
      "com.rakegroup.JoomlaOutput$Install",
      "com.rakegroup.JoomlaOutput$VectorElement",
      "org.jdom.output.Format$DefaultEscapeStrategy",
      "org.jdom.filter.OrFilter",
      "com.rakegroup.JoomlaOutput$Option",
      "com.rakegroup.JoomlaOutput$Filename",
      "org.jdom.filter.Filter",
      "org.jdom.Comment",
      "com.rakegroup.JoomlaOutput$Description",
      "com.rakegroup.JoomlaOutput$AuthorEmail",
      "org.jdom.output.Format$TextMode",
      "com.rakegroup.JoomlaOutput$Copyright",
      "org.jdom.output.Format",
      "org.jdom.output.NamespaceStack",
      "org.jdom.Content",
      "com.rakegroup.JoomlaOutput$CreationDate",
      "org.jdom.output.XMLOutputter$NamespaceStack",
      "org.jdom.CDATA",
      "com.rakegroup.JoomlaOutput$License",
      "com.rakegroup.JoomlaOutput$Languages",
      "org.jdom.DocType",
      "org.jdom.filter.AbstractFilter",
      "org.jdom.ProcessingInstruction",
      "org.jdom.DataConversionException",
      "com.rakegroup.JoomlaOutput$Positions",
      "com.rakegroup.JoomlaOutput$AuthorUrl",
      "org.jdom.EntityRef",
      "com.rakegroup.JoomlaOutput",
      "org.jdom.filter.NegateFilter",
      "com.rakegroup.JoomlaOutput$Param",
      "org.jdom.IllegalTargetException",
      "org.jdom.AttributeList",
      "org.jdom.ContentList",
      "org.jdom.output.EscapeStrategy",
      "org.jdom.IllegalAddException",
      "org.jdom.Element",
      "org.jdom.filter.AndFilter"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JoomlaOutput_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.rakegroup.JoomlaOutput",
      "org.jdom.Content",
      "org.jdom.Element",
      "com.rakegroup.JoomlaOutput$SimpleElement",
      "com.rakegroup.JoomlaOutput$VectorElement",
      "com.rakegroup.JoomlaOutput$Files",
      "org.jdom.output.Format$TextMode",
      "com.rakegroup.JoomlaOutput$Param",
      "org.jdom.AttributeList",
      "org.jdom.ContentList",
      "org.jdom.Verifier",
      "org.jdom.NamespaceKey",
      "org.jdom.Namespace",
      "org.jdom.ProcessingInstruction",
      "org.jdom.IllegalTargetException",
      "com.rakegroup.JoomlaOutput$Install",
      "com.rakegroup.JoomlaOutput$Option",
      "org.jdom.filter.AbstractFilter",
      "org.jdom.filter.ElementFilter",
      "org.jdom.DescendantIterator",
      "org.jdom.FilterIterator",
      "com.rakegroup.JoomlaOutput$Administration",
      "com.rakegroup.JoomlaOutput$License",
      "org.jdom.Attribute",
      "org.jdom.ContentList$FilterList",
      "org.jdom.ContentList$FilterListIterator",
      "com.rakegroup.JoomlaOutput$Position",
      "com.rakegroup.JoomlaOutput$Folder",
      "com.rakegroup.JoomlaOutput$Filename",
      "org.jdom.Text",
      "com.rakegroup.JoomlaOutput$Languages",
      "com.rakegroup.JoomlaOutput$AuthorEmail",
      "com.rakegroup.JoomlaOutput$CreationDate",
      "org.jdom.IllegalAddException",
      "com.rakegroup.JoomlaOutput$Name",
      "org.jdom.filter.NegateFilter",
      "com.rakegroup.JoomlaOutput$Description",
      "org.jdom.EntityRef",
      "org.jdom.IllegalNameException",
      "com.rakegroup.JoomlaOutput$Positions",
      "org.jdom.filter.ContentFilter",
      "org.jdom.filter.OrFilter",
      "com.rakegroup.JoomlaOutput$Language",
      "org.jdom.DocType",
      "com.rakegroup.JoomlaOutput$Version",
      "com.rakegroup.JoomlaOutput$Params",
      "com.rakegroup.JoomlaOutput$Author",
      "com.rakegroup.JoomlaOutput$Copyright",
      "org.jdom.output.Format",
      "org.jdom.output.Format$DefaultEscapeStrategy",
      "org.jdom.output.XMLOutputter",
      "org.jdom.Document",
      "org.jdom.output.NamespaceStack",
      "org.jdom.output.XMLOutputter$NamespaceStack",
      "org.jdom.IllegalDataException",
      "com.rakegroup.JoomlaOutput$AuthorUrl",
      "org.jdom.Comment",
      "org.jdom.CDATA",
      "org.jdom.filter.AndFilter"
    );
  }
}
