/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 10:41:20 GMT 2020
 */

package org.gudy.azureus2.core3.disk.impl.resume;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gudy.azureus2.core3.disk.DiskManagerFileInfo;
import org.gudy.azureus2.core3.disk.impl.DiskManagerFileInfoImpl;
import org.gudy.azureus2.core3.disk.impl.DiskManagerHelper;
import org.gudy.azureus2.core3.disk.impl.DiskManagerImpl;
import org.gudy.azureus2.core3.disk.impl.access.DMChecker;
import org.gudy.azureus2.core3.disk.impl.access.impl.DMCheckerImpl;
import org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler;
import org.gudy.azureus2.core3.download.DownloadManager;
import org.gudy.azureus2.core3.download.DownloadManagerState;
import org.gudy.azureus2.core3.download.impl.DownloadManagerStateImpl;
import org.gudy.azureus2.core3.torrent.TOTorrent;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RDResumeHandler_ESTest extends RDResumeHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      // Undeclared exception!
      try { 
        RDResumeHandler.setTorrentResumeDataNearlyComplete(downloadManagerState0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      HashMap<String, DiskManagerFileInfoImpl> hashMap0 = new HashMap<String, DiskManagerFileInfoImpl>();
      boolean boolean0 = RDResumeHandler.isTorrentResumeDataComplete(downloadManagerState0, (Map) hashMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      Map map0 = RDResumeHandler.getResumeData(downloadManagerState0);
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<Long, Object> hashMap0 = new HashMap<Long, Object>();
      // Undeclared exception!
      try { 
        RDResumeHandler.saveResumeData((DownloadManagerState) null, (Map) hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.isTorrentResumeDataComplete((DownloadManagerState) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.getResumeData((DownloadManagerState) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.getResumeData((DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.fileMustExist((DownloadManager) null, (DiskManagerFileInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.clearResumeDataSupport((DownloadManager) null, (DiskManagerFileInfo) null, true, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl((DiskManagerHelper) null);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler((DiskManagerImpl) null, dMCheckerImpl0);
      // Undeclared exception!
      try { 
        rDResumeHandler0.checkAllPieces(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, (DMChecker) null);
      // Undeclared exception!
      try { 
        rDResumeHandler0.checkAllPieces(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.DiskManagerRecheckScheduler", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl((DiskManagerHelper) null);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, dMCheckerImpl0);
      try { 
        rDResumeHandler0.saveResumeData(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl((DiskManagerHelper) null);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, dMCheckerImpl0);
      rDResumeHandler0.stop(true);
      rDResumeHandler0.stop(true);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl(diskManagerImpl0);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, dMCheckerImpl0);
      rDResumeHandler0.start();
      rDResumeHandler0.start();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      HashMap<String, Long> hashMap0 = new HashMap<String, Long>();
      RDResumeHandler.saveResumeData(downloadManagerState0, (Map) hashMap0);
      assertEquals(0, hashMap0.size());
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.storageTypeChanged((DownloadManager) null, (DiskManagerFileInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      // Undeclared exception!
      try { 
        RDResumeHandler.setTorrentResumeDataComplete(downloadManagerState0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DownloadManagerState downloadManagerState0 = DownloadManagerStateImpl.getDownloadState((DownloadManager) null);
      boolean boolean0 = RDResumeHandler.isTorrentResumeDataComplete(downloadManagerState0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDResumeHandler.recheckFile((DownloadManager) null, (DiskManagerFileInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl(diskManagerImpl0);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, dMCheckerImpl0);
      HashMap<DiskManagerFileInfoImpl, InputStream> hashMap0 = new HashMap<DiskManagerFileInfoImpl, InputStream>(3301);
      // Undeclared exception!
      try { 
        rDResumeHandler0.saveResumeData((Map) hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DiskManagerImpl diskManagerImpl0 = new DiskManagerImpl((TOTorrent) null, (DownloadManager) null);
      DMCheckerImpl dMCheckerImpl0 = new DMCheckerImpl(diskManagerImpl0);
      RDResumeHandler rDResumeHandler0 = new RDResumeHandler(diskManagerImpl0, dMCheckerImpl0);
      // Undeclared exception!
      try { 
        rDResumeHandler0.getResumeData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.core3.disk.impl.resume.RDResumeHandler", e);
      }
  }
}
